# Generated by Django 4.1.1 on 2022-10-20 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_rename_username_profile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_img',
            field=models.ImageField(default='profile/mysterious-mafia-man-smoking-cigarette_52683-34828.webp', upload_to='profile'),
        ),
    ]
