# Generated by Django 4.1.1 on 2022-09-27 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('video', models.ImageField(default='category/vid.jpg', upload_to='category')),
            ],
        ),
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_name', models.CharField(max_length=150)),
                ('p_img', models.ImageField(default='product/pic.jpg', upload_to='product')),
                ('p_price', models.IntegerField()),
                ('p_des', models.TextField()),
                ('P_min', models.IntegerField(default=1)),
                ('p_max', models.IntegerField()),
            ],
        ),
    ]
