# Generated by Django 4.1.1 on 2022-10-04 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_alter_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(default='a'),
        ),
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.SlugField(default='a'),
        ),
    ]
