# Generated by Django 4.1.2 on 2022-11-08 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0005_rename_address_shipping_delivery_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopcart',
            name='item_carted',
            field=models.IntegerField(default=1.0),
        ),
        migrations.AlterField(
            model_name='shipping',
            name='billing_address',
            field=models.CharField(max_length=250),
        ),
    ]
